[package]
name = "purse-proxy"
version = "0.1.0"
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"

[[bin]]
name = "purse-proxy"
path = "src/main.rs"
bench = false
doctest = false
test = false
