[package]
name = "session-code-wcspr"
version = "0.2.0"
authors = ["Bassam Monib <bassam.munib@scytalelabs.com>"]
edition = "2018"

[dependencies]
common = { path = "../../common/common" }

[[bin]]
name = "session-code-wcspr"
path = "bin/main.rs"
bench = false
doctest = false
test = false