version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.50.0
    steps:
      - run: git clone https://github.com/Rengo-Labs/CasperLabs-UniswapV2-Core.git
      - run: git clone https://github.com/Rengo-Labs/CasperLabs-UniswapV2-Router.git
      - run: sudo apt update
      - run: sudo apt install libssl-dev pkg-config
      - run: rustup install nightly-2022-08-29
      - run: rustup default nightly-2022-08-29-x86_64-unknown-linux-gnu
      - run: cargo install cargo-casper
      - run: cargo +nightly-2022-08-29-x86_64-unknown-linux-gnu install casper-client
      - run: 
          name: Build Casper Core
          command: cd CasperLabs-UniswapV2-Core && rustup target add wasm32-unknown-unknown && make all
      - run: 
          name: Build Casper Router
          command: cd CasperLabs-UniswapV2-Router && rustup target add wasm32-unknown-unknown && make all   
      - run: 
          name: Run Tests Casper Core
          command: cd CasperLabs-UniswapV2-Core && make test
      - run:
          name: Run Tests Casper Router
          command: cd CasperLabs-UniswapV2-Router && make test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - test
