[package]
name = "cryptoxide"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptoxide = "0.3.3"
renvm-sig = "0.1.1"
hex = "0.4.3"