[package]
authors = ["Muhammad Adrees <muhammad.adrees@scytalelabs.com>"]
edition = "2018"
name = "wcspr-crate"
version = "0.1.0"

[dependencies]
uniswap-erc20 = "0.1.0"
common = { path = "../../common/common" }